#ifndef CHORD_H
#define CHORD_H

#include <ctype.h>
#include <stdio.h>
#include <string.h>
#include <strings.h>

/**
 * invervals between notes defined in half steps
 */
enum interval {
	NULL_TERMINATOR = 0,
	HALF_STEP = 1,
	MAJOR_SECOND = 2,
	MINOR_THIRD = 3,
	MAJOR_THIRD = 4,
	PERFECT_FOURTH = 5,
	DIMINISHED_FIFTH = 6,
	PERFECT_FIFTH = 7,
	AUGMENTED_FIFTH = 8,
	DIMINISHED_SEVENTH = 9,
	MINOR_SEVENTH = 10,
	MAJOR_SEVENTH = 11
};

static int AUGMENTED_TRIAD_QUALITY[] = {
	MAJOR_THIRD,
	AUGMENTED_FIFTH,
	NULL_TERMINATOR
};

static int AUGMENTED_MAJOR_SEVENTH_QUALITY[] = {
	MAJOR_THIRD,
	PERFECT_FIFTH,
	MINOR_SEVENTH,
	NULL_TERMINATOR
};

static int DOMINANT_SEVENTH_QUALITY[] = {
	MAJOR_THIRD,
	PERFECT_FIFTH,
	MINOR_SEVENTH,
	NULL_TERMINATOR
};

static int DIMINISHED_SEVENTH_QUALITY[] = {
	MINOR_THIRD,
	DIMINISHED_FIFTH,
	DIMINISHED_SEVENTH,
	NULL_TERMINATOR
};

static int DIMINISHED_TRIAD_QUALITY[] = {
	MINOR_THIRD,
	DIMINISHED_FIFTH,
	NULL_TERMINATOR
};

static int MAJOR_TRIAD_QUALITY[] = {
	MAJOR_THIRD,
	PERFECT_FIFTH,
	NULL_TERMINATOR
};

static int MINOR_TRIAD_QUALITY[] = {
	MINOR_THIRD,
	PERFECT_FIFTH,
	NULL_TERMINATOR
};

static int MAJOR_SEVENTH_QUALITY[] = {
	MAJOR_THIRD,
	PERFECT_FIFTH,
	MAJOR_SEVENTH,
	NULL_TERMINATOR
};

static int MINOR_SEVENTH_QUALITY[] = {
	MINOR_THIRD,
	PERFECT_FIFTH,
	MINOR_SEVENTH,
	NULL_TERMINATOR
};

static int SUSPENDED_FOURTH_QUALITY[] = {
	PERFECT_FOURTH,
	PERFECT_FIFTH,
	NULL_TERMINATOR
};

static int SUSPENDED_SECOND_QUALITY[] = {
	MAJOR_SECOND,
	PERFECT_FIFTH,
	NULL_TERMINATOR
};

int *getquality(char *chord);

#endif /* CHORD_H */
